@ Generated by gcc 2.9-arm-000512 for Thumb/elf
	.code	16
.gcc2_compiled.:
	.globl	gBattlerPicTable_OpponentLeft
.data
	.type	 gBattlerPicTable_OpponentLeft,object
gBattlerPicTable_OpponentLeft:
	.globl	gBattlerPicTable_PlayerRight
	.type	 gBattlerPicTable_PlayerRight,object
gBattlerPicTable_PlayerRight:
	.globl	gBattlerPicTable_OpponentRight
	.type	 gBattlerPicTable_OpponentRight,object
gBattlerPicTable_OpponentRight:
	.globl	gTrainerBackPicTable_Brendan
	.type	 gTrainerBackPicTable_Brendan,object
gTrainerBackPicTable_Brendan:
	.globl	gTrainerBackPicTable_May
	.type	 gTrainerBackPicTable_May,object
gTrainerBackPicTable_May:
	.globl	gTrainerBackPicTable_Red
	.type	 gTrainerBackPicTable_Red,object
gTrainerBackPicTable_Red:
	.globl	gTrainerBackPicTable_Leaf
	.type	 gTrainerBackPicTable_Leaf,object
gTrainerBackPicTable_Leaf:
	.globl	gTrainerBackPicTable_RubySapphireBrendan
	.type	 gTrainerBackPicTable_RubySapphireBrendan,object
gTrainerBackPicTable_RubySapphireBrendan:
	.globl	gTrainerBackPicTable_RubySapphireMay
	.type	 gTrainerBackPicTable_RubySapphireMay,object
gTrainerBackPicTable_RubySapphireMay:
	.globl	gTrainerBackPicTable_Wally
	.type	 gTrainerBackPicTable_Wally,object
gTrainerBackPicTable_Wally:
	.globl	gTrainerBackPicTable_Steven
	.type	 gTrainerBackPicTable_Steven,object
gTrainerBackPicTable_Steven:
	.type	 sAnim_GeneralFrame0,object
sAnim_GeneralFrame0:
	.type	 sAnim_GeneralFrame3,object
sAnim_GeneralFrame3:
	.type	 sAffineAnim_Battler_Flipped,object
sAffineAnim_Battler_Flipped:
	.type	 sAffineAnim_Battler_Emerge,object
sAffineAnim_Battler_Emerge:
	.type	 sAffineAnim_Battler_Return,object
sAffineAnim_Battler_Return:
	.type	 sAffineAnim_Battler_HorizontalSquishLoop,object
sAffineAnim_Battler_HorizontalSquishLoop:
	.type	 sAffineAnim_Battler_Grow,object
sAffineAnim_Battler_Grow:
	.type	 sAffineAnim_Battler_Shrink,object
sAffineAnim_Battler_Shrink:
	.type	 sAffineAnim_Battler_BigToSmall,object
sAffineAnim_Battler_BigToSmall:
	.type	 sAffineAnim_Battler_GrowLarge,object
sAffineAnim_Battler_GrowLarge:
	.type	 sAffineAnim_Battler_TipRight,object
sAffineAnim_Battler_TipRight:
	.globl	gAffineAnims_BattleSpritePlayerSide
	.section .rodata
	.align	2, 0
	.type	 gAffineAnims_BattleSpritePlayerSide,object
gAffineAnims_BattleSpritePlayerSide:
	.space	4
	.word	sAffineAnim_Battler_Emerge
	.word	sAffineAnim_Battler_Return
	.word	sAffineAnim_Battler_HorizontalSquishLoop
	.word	sAffineAnim_Battler_Grow
	.word	sAffineAnim_Battler_Shrink
	.word	sAffineAnim_Battler_GrowLarge
	.word	sAffineAnim_Battler_TipRight
	.word	sAffineAnim_Battler_BigToSmall
	.size	 gAffineAnims_BattleSpritePlayerSide,36
.data
	.type	 sAffineAnim_Battler_SpinShrink,object
sAffineAnim_Battler_SpinShrink:
	.type	 sAffineAnim_Battler_TipLeft,object
sAffineAnim_Battler_TipLeft:
	.type	 sAffineAnim_Battler_RotateUpAndBack,object
sAffineAnim_Battler_RotateUpAndBack:
	.type	 sAffineAnim_Battler_Spin,object
sAffineAnim_Battler_Spin:
	.globl	gAffineAnims_BattleSpriteOpponentSide
	.section .rodata
	.align	2, 0
	.type	 gAffineAnims_BattleSpriteOpponentSide,object
gAffineAnims_BattleSpriteOpponentSide:
	.space	4
	.word	sAffineAnim_Battler_Emerge
	.word	sAffineAnim_Battler_Return
	.word	sAffineAnim_Battler_HorizontalSquishLoop
	.word	sAffineAnim_Battler_Grow
	.word	sAffineAnim_Battler_Shrink
	.word	sAffineAnim_Battler_SpinShrink
	.word	sAffineAnim_Battler_TipLeft
	.word	sAffineAnim_Battler_RotateUpAndBack
	.word	sAffineAnim_Battler_BigToSmall
	.word	sAffineAnim_Battler_Spin
	.size	 gAffineAnims_BattleSpriteOpponentSide,44
	.globl	gAffineAnims_BattleSpriteContest
	.align	2, 0
	.type	 gAffineAnims_BattleSpriteContest,object
gAffineAnims_BattleSpriteContest:
	.word	sAffineAnim_Battler_Flipped
	.word	sAffineAnim_Battler_Emerge
	.word	sAffineAnim_Battler_Return
	.word	sAffineAnim_Battler_HorizontalSquishLoop
	.word	sAffineAnim_Battler_Grow
	.word	sAffineAnim_Battler_Shrink
	.word	sAffineAnim_Battler_SpinShrink
	.word	sAffineAnim_Battler_TipLeft
	.word	sAffineAnim_Battler_RotateUpAndBack
	.word	sAffineAnim_Battler_BigToSmall
	.word	sAffineAnim_Battler_Spin
	.size	 gAffineAnims_BattleSpriteContest,44
.data
	.type	 sAnim_MonPic_0,object
sAnim_MonPic_0:
	.type	 sAnim_MonPic_1,object
sAnim_MonPic_1:
	.type	 sAnim_MonPic_2,object
sAnim_MonPic_2:
	.type	 sAnim_MonPic_3,object
sAnim_MonPic_3:
	.globl	gAnims_MonPic
	.type	 gAnims_MonPic,object
	.size	 gAnims_MonPic,0
gAnims_MonPic:
	.comm	gMinigameDigits_Pal, 4	@ 4
	.comm	gMinigameDigits_Gfx, 4	@ 4
	.comm	sMinigameDigitsThin_Gfx, 4	@ 4
